### ISSUE TITLE
Blog: Matrix organization administration experience and how to do it without hosting a server and thus without Mjolnir

### ISSUE THREAD

**Issue by Mikaela** [Mikaela/mikaela.github.io#268]
I think Matrix is currently designed for the case where every organization runs their own server and their own Mjolnir which has all the useful features, so this will come across as a critique regardless of how it's done. I have the personal spaces and rooms, but they aren't as interesting as @Piraattipuolue which situation is https://git.piraattipuolue.fi/Pikaviestimet/Pikaviestimet/src/branch/master/kanavat.csv : 

* A public space and a restricted space, total 2 spaces
* ➕  14 public rooms
* ➕ 9 private rooms

How to use Matrix or Element? A lot of doing things by hand.

* `/devtools` is your best friend or at least the way to perform things somewhat reasonably.
* When making a room, make it within a space so it will be automatically version 9 to hopefully have some tool for protecting against spam in the future.
* Copy-paste https://gitea.blesmrt.net/mikaela/gist/src/branch/master/matrix/m.room.power_levels to make people as ops.
  * well actually https://git.piraattipuolue.fi/Pikaviestimet/Pikaviestimet/issues/11
* Tell matterbridge the room exists (no own server, no pretty puppets (#246)
* Don't forget to `/devtools` the private space into knocking only as restricted-knocking cannot be merged
  * also explain the blog what that means
* Malicious user? Copy-paste the ban to every room, we don't have a server so no nice server extension to do it.
* Malicious server? You guessed it, `/devtools` copy-paste time across the rooms!
* Are things really so bad? No, unless we approve a malicious user into the restricted working peace space.

**Comment by Mikaela** [comment]
Why is there no server? We don't have human resources or money for it. Our Matrix existence is one person (me) show for existing at all.

What is wrong with requiring running a server for proper moderation and bridges? Matrix is a federated protocol, own server to run a server extension (Mjolnir) is a single point of failure and they aren't moved around as easily (Matterbridge: swap server, username and password fields, spam `/invite @matterbridge:example.net` everywhere).

Obligatory, but aren't rooms centralized anyway? No, they are hosted on all servers that have users in the room and it's good practice to have administrator access on multiple servers in case one went down for whatever reason.

**Comment by Mikaela** [comment]
It should begin with overview including the spaces and that the matterbridge has owner everywhere (account sharing) to avoid my bus factor as so far I am the only one to actively touch Matrix in depth from the ICT team to my knowledge.

Invite-only vs knocking? The rooms in working peace space are public, their point is to avoid distruption to party operations should abuse happen, anyone shown to not be malicious is let in so it's not supposed to be invite only. Then again at the time of writing it kind of it as clients implementing knocking are a minority and I can only name Nheko.

Should I open how spaces work on pointing to other rooms and their vias that never seem to update so I am just hoping for those servers to never go down? I discussed it with @Sorunome offline, but I don't remember what was the verdict, was that something no one else had thought of before?

**Comment by Mikaela** [comment]
Bonus: https://github.com/vector-im/element-web/issues/19208 & https://github.com/vector-im/element-web/issues/19841 to make knocking an option at all, because both spaces started at version 6. However I am optimistic that the issues may be resolved before I have time to blog about this unless I get sudden inspiration.

I should also post the json's in this post to make it more clear what is being done.

**Comment by Mikaela** [comment]
Additional plan: I can advice user to perform `/upgraderoom {{ site.matrixLatestRoomVersion }]` as I am [bound to refer to it often](https://github.com/Mikaela/mikaela.github.io/issues?q=is%3Aissue+is%3Aopen+label%3A%5Bm%5D) and then just change `config.yml` without having to wonder what room versions do my posts refer to.

**Comment by vintprox** [comment]
Good day to you, @Mikaela! I found your blog after listing through some `element-web` issue. Good read! It seemed especially relevant to me as I also started managing a small space on Matrix which I call "dR Community Matrix". I plan to open it for more devRant users out there once it's all tidy and lean.

Doubling down on verification procedure, as this idea succeeded on my Discord server for devRant, which kind of prevents "identity" theft. I'm taking it beyond user-bot interaction by developing a graphical widget (SvelteKit/HTML+CSS+JavaScript). I plan to add there some extras: workshop planning, showcase, music collection, meme generator, etc. (they all are secondary advancements against infinite scrolling and switching between tabs/apps).

So how is this relevant? Well, while I can just host my widget on GitHub Pages without problem, receiving input from a user on room/space level will require some sort of backend. Zero-price requirement arrises more in face of a service that's supposed to work even if I abandon it. (Yet another reason why I don't host my own Synapse/Conduit instance. I don't want to seem like I have hidden power level above other admins in our community rooms, because I believe this place should be supervised equally between room admins, without one devRant persona puppeting everything.)

When it comes to decent free tier backend, only Heroku comes to mind. Luckily, I don't have any dynos running on my account, so I can allocate one free worker dyno to run a bot. Bot will receive Matrix events that are constructed by widget on behalf of user, and also send events back that widget can see. In theory, it eliminates the need for exposing HTTP endpoints with all possible freezes from Heroku in favor of a continuous process.

> Additional plan: I can advice user to perform `/upgraderoom {{ site.matrixLatestRoomVersion }]` as I am [bound to refer to it often](https://github.com/Mikaela/mikaela.github.io/issues?q=is%3Aissue+is%3Aopen+label%3A%5Bm%5D) and then just change `config.yml` without having to wonder what room versions do my posts refer to.

The amount of thought put into this blog post as other your posts is astounding, which is very-very great! Keep going 😄
